version: '3'

services:
    db:
        image: mysql:5.7
        container_name: mysql_db_tests
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: snippetbox_test
            MYSQL_USER: user
            MYSQL_PASSWORD: 123
        restart: always
        volumes:
            - ./my-test-volume:/var/lib/mysql